### ISSUE TITLE
Event notification by Email

### ISSUE THREAD

**Issue by amio** [amio/eb#17]
当 hourly 错误超过一定阀值的时候发出 email 通知

**Comment by codinfox** [comment]
你觉得我们是引入redis做这个功能呢还是就是用现有的东西做？ @amio

**Comment by amio** [comment]
先在现有基础上做。

**Comment by codinfox** [comment]
@amio 几个问题：
1. 我们的“hourly”怎么界定，是真实的一个小时（整点）还是任意一个小时，即只要error超过阈值，且第一条和最后一条的时间差是一个小时我们就报错误
2. 假设我们的阈值是100，第一分钟报了100个error，是立刻发邮件还是等到一个小时的时候发邮件？
3. 假设我们的阈值是100，第一分钟报了99个error，第二分钟报了2个，第三分钟报了2个，那么是一小时之内只报一次还是报多次（第二分钟第三分钟都报）

---

我现在的想法是：

只要error超过阈值，且第一条和最后一条的时间差是一个小时我们就报错误，报错之后计数器清空重新开始计数，效果是只要一个小时之内报错数量超过阈值就发邮件，发过邮件之后的一个小时之内如果又超过就再发。如果发过邮件之后的一分钟之内错误就超过阈值，则一分钟之内就再发邮件……

**Comment by amio** [comment]
不错，问题想得挺清楚了

但是这个方法计算压力略大，每来一条 error 都得做判断和计算，线上真有状况的时候每秒很可能会上万条错误，et 来不及发邮件自己就被ddos挂了

我想的比较简单，按真实的时间段来判断就行了，每隔一段时间执行一下统计，基于两个考虑：
1. 真实线上环境如果发生了需要关注的错误，应该会有非常显著的峰值
2. 结合 #18 ，提高监测的精确度，将来这个间隔也许可以改成每分钟（whatever，看我们需要的精度和服务器压力调整）

**Comment by amio** [comment]
你收到有报警邮件吗？我这里一封都没有
阀值过高了么？调到每 10 分钟 100 错吧。

**Comment by codinfox** [comment]
我也一封没有 我先看看有没有报错

**Comment by codinfox** [comment]
上线的代码有点问题，recipient拼成receipient了。之前在本地config.json里面也拼错了，所以在本地能测试通过，在线上的config.json拼写是对的就过不了了。

我现在修改成了10分钟10个错，过一会看看能不能收到邮件。 @amio

**Comment by amio** [comment]
有了
