### ISSUE TITLE
邮件内容变成了附件

### ISSUE THREAD

**Issue by amio** [amio/eb#35]
内容丰富多了，不过现在是附件下载，不是邮件正文

![image](https://cloud.githubusercontent.com/assets/215282/7178842/a4525a98-e464-11e4-8cb8-e778c6daeff5.png)

**Comment by codinfox** [comment]
嗯 我发现这个问题了
不过不太稳定，有时候是附件有时候不是，我怀疑可能是邮件内容太大的原因？或者是内容有什么特殊的符号？再查查 = =

https://forums.opensuse.org/showthread.php/445955-mailx-creates-unwanted-attachment

**Comment by amio** [comment]
今天又收到一封是正常的

**Comment by amio** [comment]
btw，可以考虑把 [count 123] 放到行首

**Comment by amio** [comment]
![image](https://cloud.githubusercontent.com/assets/215282/7223297/8d839062-e751-11e4-94e2-e5bde728a587.png)
有时候是正文有时候是附件
