### ISSUE TITLE
清理过期数据

### ISSUE THREAD

**Issue by amio** [amio/eb#36]
清理数据库里超过4天的信息

**Comment by amio** [comment]
部署了么？看起来 message 里还有4月21日的数据

**Comment by codinfox** [comment]
部署了 现在的策略是14天

**Comment by amio** [comment]
我改成4天了， dashboard 里也只显示4天，多的数据不存了。

话说 Issue 本来计划的是清理 4d+ 的数据，
你做的是清理 14d+，关 Issue 也没有对此注释，忘了还是没注意？
