### ISSUE TITLE
替换掉nedb数据库以提升查询性能

### ISSUE THREAD

**Issue by codinfox** [amio/eb#38]
1. 将数据库切换到mongo，期待获得更好的查询和插入性能
2. 将mongo/nedb的选择作为配置项，尽可能保留两套逻辑

@amio 啥意见？
# 

4.23更新：

RethinkDB确实是一个很好地选择，考虑支持一下。
那初步决定放弃对NeDB的支持，另开branch，重打版本号。

**Comment by amio** [comment]
1. 数据库选择  
   Mongo 肯定是个OK，不过也不排除其他更好的可能，动手之前我依然考虑多花点时间横向比较下所有可能的选项。  
   最近 RethinkDB 刚发了 2.0，不少人涌出来叫好，目测也确实值得关注一下。对我们来说实时推送特性很赞，Dashboard 会借此成为个亮点，性能方面貌似反馈也很好（1.x的时候被人吐槽过，2.0貌似很NB了）。
2. 我估计保留 nedb 的支持会拖后腿。类似浏览器兼容的场景，要想支持低级浏览器就得放弃某些高级特性。nedb 和 mongodb 的差异如果只是性能那很好，只是可能性不大吧。想要尽量保留 nedb 的支持是挺好的，把它当做优先级较低的考量好了。实现以针对 mongodb 优先，可能的话顺便支持 nedb。
