### ISSUE TITLE
服务器性能缺陷

### ISSUE THREAD

**Issue by codinfox** [amio/eb#50]
现在服务器的内存占用率居高不下，尚不清楚造成问题的原因。现在我的猜想是NeDB会在内存当中维护数据的一部分信息？比如索引？不知道迁移数据库能不能解决这个问题。

除此之外，能否考虑增加一下服务器的内存？现在物理内存才不到1G，加上swap也不到2G……另，因为现在存在的一些负载的问题，我们可不可能搭建分布式的服务？目前我们的数据量才是真实数据量的千分之一，真正加到真实数据量现在的配置是不是有点吃不消啊。

@amio

**Comment by amio** [comment]
有可能是 nedb 的缺陷，也可能是我们的实现暴露了它的短板，不过需要定位出来问题才能下结论。

1G确实小了，稍后我去申请下增加点配置，
不过在这之前我们最好先把性能问题查清楚，到底问题出在哪里，能优化的优化，
然后再调整服务器配置。
