### ISSUE TITLE
是不是考虑把nedb的版本单独拉出来

### ISSUE THREAD

**Issue by codinfox** [amio/eb#54]
做一个新项目或者跟mongo版本平行的版本什么的，毕竟nedb免配置，符合lapple的想法

**Comment by hax** [comment]
优先级比较低。或许应该考虑的是store层本身是否要可插拔。

**Comment by codinfox** [comment]
嗯。。。
考虑到这个项目本身对于数据库操作的复杂度较低，没有什么复杂的建模，所以也没有使用ORM。
现在的方案如果需要更换store的话需要重写查询和插入方法，不过都已经封装到相应的文件了，所以不会影响其他部分的代码。 @hax

**Comment by amio** [comment]
NeDB 的 api 是 MongoDB 的子集，兼容成本应该不会太高吧

**Comment by codinfox** [comment]
不算低 因为我们主要的就是聚合，mongo是支持的 但nedb不支持 这就是为什么之前lapple手写聚合逻辑的原因

**Comment by amio** [comment]
蛋疼，那估计这是条不归路了。

NeDB 的支持留在 Lapple 那个仓库里吧，正好他的愿景是支持个人用户轻便上手，而我们的目标是支持企业应用。

**Comment by codinfox** [comment]
OK👌
